--- # My first YAML playbook for ansible

- hosts: apacheweb
  user:  test
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
   playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: web_domain
      prompt: Web Domain
